{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "cff93368",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[{'name': 'Tatooine', 'rotation_period': '23', 'orbital_period': '304', 'diameter': '10465', 'climate': 'arid', 'gravity': '1 standard', 'terrain': 'desert', 'surface_water': '1', 'population': '200000', 'residents': ['https://swapi.dev/api/people/1/', 'https://swapi.dev/api/people/2/', 'https://swapi.dev/api/people/4/', 'https://swapi.dev/api/people/6/', 'https://swapi.dev/api/people/7/', 'https://swapi.dev/api/people/8/', 'https://swapi.dev/api/people/9/', 'https://swapi.dev/api/people/11/', 'https://swapi.dev/api/people/43/', 'https://swapi.dev/api/people/62/'], 'films': ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'], 'created': '2014-12-09T13:50:49.641000Z', 'edited': '2014-12-20T20:58:18.411000Z', 'url': 'https://swapi.dev/api/planets/1/'}, {'name': 'Alderaan', 'rotation_period': '24', 'orbital_period': '364', 'diameter': '12500', 'climate': 'temperate', 'gravity': '1 standard', 'terrain': 'grasslands, mountains', 'surface_water': '40', 'population': '2000000000', 'residents': ['https://swapi.dev/api/people/5/', 'https://swapi.dev/api/people/68/', 'https://swapi.dev/api/people/81/'], 'films': ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/6/'], 'created': '2014-12-10T11:35:48.479000Z', 'edited': '2014-12-20T20:58:18.420000Z', 'url': 'https://swapi.dev/api/planets/2/'}, {'name': 'Yavin IV', 'rotation_period': '24', 'orbital_period': '4818', 'diameter': '10200', 'climate': 'temperate, tropical', 'gravity': '1 standard', 'terrain': 'jungle, rainforests', 'surface_water': '8', 'population': '1000', 'residents': [], 'films': ['https://swapi.dev/api/films/1/'], 'created': '2014-12-10T11:37:19.144000Z', 'edited': '2014-12-20T20:58:18.421000Z', 'url': 'https://swapi.dev/api/planets/3/'}, {'name': 'Hoth', 'rotation_period': '23', 'orbital_period': '549', 'diameter': '7200', 'climate': 'frozen', 'gravity': '1.1 standard', 'terrain': 'tundra, ice caves, mountain ranges', 'surface_water': '100', 'population': 'unknown', 'residents': [], 'films': ['https://swapi.dev/api/films/2/'], 'created': '2014-12-10T11:39:13.934000Z', 'edited': '2014-12-20T20:58:18.423000Z', 'url': 'https://swapi.dev/api/planets/4/'}, {'name': 'Dagobah', 'rotation_period': '23', 'orbital_period': '341', 'diameter': '8900', 'climate': 'murky', 'gravity': 'N/A', 'terrain': 'swamp, jungles', 'surface_water': '8', 'population': 'unknown', 'residents': [], 'films': ['https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/6/'], 'created': '2014-12-10T11:42:22.590000Z', 'edited': '2014-12-20T20:58:18.425000Z', 'url': 'https://swapi.dev/api/planets/5/'}, {'name': 'Bespin', 'rotation_period': '12', 'orbital_period': '5110', 'diameter': '118000', 'climate': 'temperate', 'gravity': '1.5 (surface), 1 standard (Cloud City)', 'terrain': 'gas giant', 'surface_water': '0', 'population': '6000000', 'residents': ['https://swapi.dev/api/people/26/'], 'films': ['https://swapi.dev/api/films/2/'], 'created': '2014-12-10T11:43:55.240000Z', 'edited': '2014-12-20T20:58:18.427000Z', 'url': 'https://swapi.dev/api/planets/6/'}, {'name': 'Endor', 'rotation_period': '18', 'orbital_period': '402', 'diameter': '4900', 'climate': 'temperate', 'gravity': '0.85 standard', 'terrain': 'forests, mountains, lakes', 'surface_water': '8', 'population': '30000000', 'residents': ['https://swapi.dev/api/people/30/'], 'films': ['https://swapi.dev/api/films/3/'], 'created': '2014-12-10T11:50:29.349000Z', 'edited': '2014-12-20T20:58:18.429000Z', 'url': 'https://swapi.dev/api/planets/7/'}, {'name': 'Naboo', 'rotation_period': '26', 'orbital_period': '312', 'diameter': '12120', 'climate': 'temperate', 'gravity': '1 standard', 'terrain': 'grassy hills, swamps, forests, mountains', 'surface_water': '12', 'population': '4500000000', 'residents': ['https://swapi.dev/api/people/3/', 'https://swapi.dev/api/people/21/', 'https://swapi.dev/api/people/35/', 'https://swapi.dev/api/people/36/', 'https://swapi.dev/api/people/37/', 'https://swapi.dev/api/people/38/', 'https://swapi.dev/api/people/39/', 'https://swapi.dev/api/people/42/', 'https://swapi.dev/api/people/60/', 'https://swapi.dev/api/people/61/', 'https://swapi.dev/api/people/66/'], 'films': ['https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'], 'created': '2014-12-10T11:52:31.066000Z', 'edited': '2014-12-20T20:58:18.430000Z', 'url': 'https://swapi.dev/api/planets/8/'}, {'name': 'Coruscant', 'rotation_period': '24', 'orbital_period': '368', 'diameter': '12240', 'climate': 'temperate', 'gravity': '1 standard', 'terrain': 'cityscape, mountains', 'surface_water': 'unknown', 'population': '1000000000000', 'residents': ['https://swapi.dev/api/people/34/', 'https://swapi.dev/api/people/55/', 'https://swapi.dev/api/people/74/'], 'films': ['https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'], 'created': '2014-12-10T11:54:13.921000Z', 'edited': '2014-12-20T20:58:18.432000Z', 'url': 'https://swapi.dev/api/planets/9/'}]\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>name</th>\n",
       "      <th>rotation_period</th>\n",
       "      <th>orbital_period</th>\n",
       "      <th>diameter</th>\n",
       "      <th>climate</th>\n",
       "      <th>gravity</th>\n",
       "      <th>terrain</th>\n",
       "      <th>surface_water</th>\n",
       "      <th>population</th>\n",
       "      <th>residents</th>\n",
       "      <th>films</th>\n",
       "      <th>created</th>\n",
       "      <th>edited</th>\n",
       "      <th>url</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Tatooine</td>\n",
       "      <td>23</td>\n",
       "      <td>304</td>\n",
       "      <td>10465</td>\n",
       "      <td>arid</td>\n",
       "      <td>1 standard</td>\n",
       "      <td>desert</td>\n",
       "      <td>1</td>\n",
       "      <td>200000</td>\n",
       "      <td>[https://swapi.dev/api/people/1/, https://swap...</td>\n",
       "      <td>[https://swapi.dev/api/films/1/, https://swapi...</td>\n",
       "      <td>2014-12-09T13:50:49.641000Z</td>\n",
       "      <td>2014-12-20T20:58:18.411000Z</td>\n",
       "      <td>https://swapi.dev/api/planets/1/</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Alderaan</td>\n",
       "      <td>24</td>\n",
       "      <td>364</td>\n",
       "      <td>12500</td>\n",
       "      <td>temperate</td>\n",
       "      <td>1 standard</td>\n",
       "      <td>grasslands, mountains</td>\n",
       "      <td>40</td>\n",
       "      <td>2000000000</td>\n",
       "      <td>[https://swapi.dev/api/people/5/, https://swap...</td>\n",
       "      <td>[https://swapi.dev/api/films/1/, https://swapi...</td>\n",
       "      <td>2014-12-10T11:35:48.479000Z</td>\n",
       "      <td>2014-12-20T20:58:18.420000Z</td>\n",
       "      <td>https://swapi.dev/api/planets/2/</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Yavin IV</td>\n",
       "      <td>24</td>\n",
       "      <td>4818</td>\n",
       "      <td>10200</td>\n",
       "      <td>temperate, tropical</td>\n",
       "      <td>1 standard</td>\n",
       "      <td>jungle, rainforests</td>\n",
       "      <td>8</td>\n",
       "      <td>1000</td>\n",
       "      <td>[]</td>\n",
       "      <td>[https://swapi.dev/api/films/1/]</td>\n",
       "      <td>2014-12-10T11:37:19.144000Z</td>\n",
       "      <td>2014-12-20T20:58:18.421000Z</td>\n",
       "      <td>https://swapi.dev/api/planets/3/</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Hoth</td>\n",
       "      <td>23</td>\n",
       "      <td>549</td>\n",
       "      <td>7200</td>\n",
       "      <td>frozen</td>\n",
       "      <td>1.1 standard</td>\n",
       "      <td>tundra, ice caves, mountain ranges</td>\n",
       "      <td>100</td>\n",
       "      <td>unknown</td>\n",
       "      <td>[]</td>\n",
       "      <td>[https://swapi.dev/api/films/2/]</td>\n",
       "      <td>2014-12-10T11:39:13.934000Z</td>\n",
       "      <td>2014-12-20T20:58:18.423000Z</td>\n",
       "      <td>https://swapi.dev/api/planets/4/</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Dagobah</td>\n",
       "      <td>23</td>\n",
       "      <td>341</td>\n",
       "      <td>8900</td>\n",
       "      <td>murky</td>\n",
       "      <td>N/A</td>\n",
       "      <td>swamp, jungles</td>\n",
       "      <td>8</td>\n",
       "      <td>unknown</td>\n",
       "      <td>[]</td>\n",
       "      <td>[https://swapi.dev/api/films/2/, https://swapi...</td>\n",
       "      <td>2014-12-10T11:42:22.590000Z</td>\n",
       "      <td>2014-12-20T20:58:18.425000Z</td>\n",
       "      <td>https://swapi.dev/api/planets/5/</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Bespin</td>\n",
       "      <td>12</td>\n",
       "      <td>5110</td>\n",
       "      <td>118000</td>\n",
       "      <td>temperate</td>\n",
       "      <td>1.5 (surface), 1 standard (Cloud City)</td>\n",
       "      <td>gas giant</td>\n",
       "      <td>0</td>\n",
       "      <td>6000000</td>\n",
       "      <td>[https://swapi.dev/api/people/26/]</td>\n",
       "      <td>[https://swapi.dev/api/films/2/]</td>\n",
       "      <td>2014-12-10T11:43:55.240000Z</td>\n",
       "      <td>2014-12-20T20:58:18.427000Z</td>\n",
       "      <td>https://swapi.dev/api/planets/6/</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Endor</td>\n",
       "      <td>18</td>\n",
       "      <td>402</td>\n",
       "      <td>4900</td>\n",
       "      <td>temperate</td>\n",
       "      <td>0.85 standard</td>\n",
       "      <td>forests, mountains, lakes</td>\n",
       "      <td>8</td>\n",
       "      <td>30000000</td>\n",
       "      <td>[https://swapi.dev/api/people/30/]</td>\n",
       "      <td>[https://swapi.dev/api/films/3/]</td>\n",
       "      <td>2014-12-10T11:50:29.349000Z</td>\n",
       "      <td>2014-12-20T20:58:18.429000Z</td>\n",
       "      <td>https://swapi.dev/api/planets/7/</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Naboo</td>\n",
       "      <td>26</td>\n",
       "      <td>312</td>\n",
       "      <td>12120</td>\n",
       "      <td>temperate</td>\n",
       "      <td>1 standard</td>\n",
       "      <td>grassy hills, swamps, forests, mountains</td>\n",
       "      <td>12</td>\n",
       "      <td>4500000000</td>\n",
       "      <td>[https://swapi.dev/api/people/3/, https://swap...</td>\n",
       "      <td>[https://swapi.dev/api/films/3/, https://swapi...</td>\n",
       "      <td>2014-12-10T11:52:31.066000Z</td>\n",
       "      <td>2014-12-20T20:58:18.430000Z</td>\n",
       "      <td>https://swapi.dev/api/planets/8/</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>Coruscant</td>\n",
       "      <td>24</td>\n",
       "      <td>368</td>\n",
       "      <td>12240</td>\n",
       "      <td>temperate</td>\n",
       "      <td>1 standard</td>\n",
       "      <td>cityscape, mountains</td>\n",
       "      <td>unknown</td>\n",
       "      <td>1000000000000</td>\n",
       "      <td>[https://swapi.dev/api/people/34/, https://swa...</td>\n",
       "      <td>[https://swapi.dev/api/films/3/, https://swapi...</td>\n",
       "      <td>2014-12-10T11:54:13.921000Z</td>\n",
       "      <td>2014-12-20T20:58:18.432000Z</td>\n",
       "      <td>https://swapi.dev/api/planets/9/</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "        name rotation_period orbital_period diameter              climate  \\\n",
       "0   Tatooine              23            304    10465                 arid   \n",
       "1   Alderaan              24            364    12500            temperate   \n",
       "2   Yavin IV              24           4818    10200  temperate, tropical   \n",
       "3       Hoth              23            549     7200               frozen   \n",
       "4    Dagobah              23            341     8900                murky   \n",
       "5     Bespin              12           5110   118000            temperate   \n",
       "6      Endor              18            402     4900            temperate   \n",
       "7      Naboo              26            312    12120            temperate   \n",
       "8  Coruscant              24            368    12240            temperate   \n",
       "\n",
       "                                  gravity  \\\n",
       "0                              1 standard   \n",
       "1                              1 standard   \n",
       "2                              1 standard   \n",
       "3                            1.1 standard   \n",
       "4                                     N/A   \n",
       "5  1.5 (surface), 1 standard (Cloud City)   \n",
       "6                           0.85 standard   \n",
       "7                              1 standard   \n",
       "8                              1 standard   \n",
       "\n",
       "                                    terrain surface_water     population  \\\n",
       "0                                    desert             1         200000   \n",
       "1                     grasslands, mountains            40     2000000000   \n",
       "2                       jungle, rainforests             8           1000   \n",
       "3        tundra, ice caves, mountain ranges           100        unknown   \n",
       "4                            swamp, jungles             8        unknown   \n",
       "5                                 gas giant             0        6000000   \n",
       "6                 forests, mountains, lakes             8       30000000   \n",
       "7  grassy hills, swamps, forests, mountains            12     4500000000   \n",
       "8                      cityscape, mountains       unknown  1000000000000   \n",
       "\n",
       "                                           residents  \\\n",
       "0  [https://swapi.dev/api/people/1/, https://swap...   \n",
       "1  [https://swapi.dev/api/people/5/, https://swap...   \n",
       "2                                                 []   \n",
       "3                                                 []   \n",
       "4                                                 []   \n",
       "5                 [https://swapi.dev/api/people/26/]   \n",
       "6                 [https://swapi.dev/api/people/30/]   \n",
       "7  [https://swapi.dev/api/people/3/, https://swap...   \n",
       "8  [https://swapi.dev/api/people/34/, https://swa...   \n",
       "\n",
       "                                               films  \\\n",
       "0  [https://swapi.dev/api/films/1/, https://swapi...   \n",
       "1  [https://swapi.dev/api/films/1/, https://swapi...   \n",
       "2                   [https://swapi.dev/api/films/1/]   \n",
       "3                   [https://swapi.dev/api/films/2/]   \n",
       "4  [https://swapi.dev/api/films/2/, https://swapi...   \n",
       "5                   [https://swapi.dev/api/films/2/]   \n",
       "6                   [https://swapi.dev/api/films/3/]   \n",
       "7  [https://swapi.dev/api/films/3/, https://swapi...   \n",
       "8  [https://swapi.dev/api/films/3/, https://swapi...   \n",
       "\n",
       "                       created                       edited  \\\n",
       "0  2014-12-09T13:50:49.641000Z  2014-12-20T20:58:18.411000Z   \n",
       "1  2014-12-10T11:35:48.479000Z  2014-12-20T20:58:18.420000Z   \n",
       "2  2014-12-10T11:37:19.144000Z  2014-12-20T20:58:18.421000Z   \n",
       "3  2014-12-10T11:39:13.934000Z  2014-12-20T20:58:18.423000Z   \n",
       "4  2014-12-10T11:42:22.590000Z  2014-12-20T20:58:18.425000Z   \n",
       "5  2014-12-10T11:43:55.240000Z  2014-12-20T20:58:18.427000Z   \n",
       "6  2014-12-10T11:50:29.349000Z  2014-12-20T20:58:18.429000Z   \n",
       "7  2014-12-10T11:52:31.066000Z  2014-12-20T20:58:18.430000Z   \n",
       "8  2014-12-10T11:54:13.921000Z  2014-12-20T20:58:18.432000Z   \n",
       "\n",
       "                                url  \n",
       "0  https://swapi.dev/api/planets/1/  \n",
       "1  https://swapi.dev/api/planets/2/  \n",
       "2  https://swapi.dev/api/planets/3/  \n",
       "3  https://swapi.dev/api/planets/4/  \n",
       "4  https://swapi.dev/api/planets/5/  \n",
       "5  https://swapi.dev/api/planets/6/  \n",
       "6  https://swapi.dev/api/planets/7/  \n",
       "7  https://swapi.dev/api/planets/8/  \n",
       "8  https://swapi.dev/api/planets/9/  "
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import requests\n",
    "import pandas as pd\n",
    "\n",
    "uri = 'https://swapi.dev/api/planets'\n",
    "\n",
    "n_planets = 10\n",
    "data = []\n",
    "for i in range(1, n_planets):\n",
    "    response = requests.get(f'{uri}/{str(i)}')\n",
    "    if response.status_code == 200:\n",
    "        data.append(response.json())\n",
    "    else: \n",
    "        data = []\n",
    "        \n",
    "print(data)\n",
    "\n",
    "columns = ['name','rotation_period','orbital_period', \"diameter\", \"climate\", \"gravity\", \"terrain\", \"surface_water\", \"population\", \"residents\", \"films\", \"created\", \"edited\",\"url\"]\n",
    "planets_df = pd.DataFrame(columns=columns)\n",
    "planets_df\n",
    "\n",
    "data\n",
    "\n",
    "for index, row in enumerate(data):\n",
    "    \n",
    "    planets_df.loc[index,'name'] = row['name']\n",
    "    planets_df.loc[index,'rotation_period'] = row['rotation_period']\n",
    "    planets_df.loc[index,'orbital_period'] = row['orbital_period']\n",
    "    planets_df.loc[index,'diameter'] = row['diameter']\n",
    "    planets_df.loc[index,'climate'] = row['climate']\n",
    "    planets_df.loc[index,'gravity'] = row['gravity']\n",
    "    planets_df.loc[index,'terrain'] = row['terrain']\n",
    "    planets_df.loc[index,'surface_water'] = row['surface_water']\n",
    "    planets_df.loc[index,'population'] = row['population']\n",
    "    planets_df.loc[index,'residents'] = row['residents']\n",
    "    planets_df.loc[index,'films'] = row['films']\n",
    "    planets_df.loc[index,'created'] = row['created']\n",
    "    planets_df.loc[index,'edited'] = row['edited']\n",
    "    planets_df.loc[index,'url'] = row['url']\n",
    "    \n",
    "planets_df\n",
    "   "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "15320280",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3dd36861",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
